const _ = require('lodash');
const logger = require('morgan');
const express = require("express");

const app = express();
const port = process.env.PORT || 3000;

app.set('port', port);
app.use(logger('dev'));

const countries = [
	['Afghanistan', 'Asia', '93', 'AF', 'AFG'],
    ['Albania', 'Europe', '355', 'AL', 'ALB'],
    ['Algeria', 'Africa', '213', 'DZ', 'DZA'],
    ['American Samoa', 'Australia', '1-684', 'AS', 'ASM'],
    ['Andorra', 'Europe', '376', 'AD', 'AND'],
    ['Angola', 'Africa', '244', 'AO', 'AGO'],
    ['Anguilla', 'America', '1-264', 'AI', 'AIA'],
    ['Antarctica', '', '672', 'AQ', 'ATA'],
    ['Antigua and Barbuda', 'America', '1-268', 'AG', 'ATG'],
    ['Argentina', 'America', '54', 'AR', 'ARG'],
    ['Armenia', 'Asia', '374', 'AM', 'ARM'],
    ['Aruba', 'America', '297', 'AW', 'ABW'],
    ['Australia', 'Australia', '61', 'AU', 'AUS'],
    ['Austria', 'Europe', '43', 'AT', 'AUT'],
    ['Azerbaijan', 'Asia', '994', 'AZ', 'AZE'],
    ['Bahamas', 'America', '1-242', 'BS', 'BHS'],
    ['Bahrain', 'Asia', '973', 'BH', 'BHR'],
    ['Bangladesh', 'Asia', '880', 'BD', 'BGD'],
    ['Barbados', '', '1-246', 'BB', 'BRB'],
    ['Belarus', 'Europe', '375', 'BY', 'BLR'],
    ['Belgium', 'Europe', '32', 'BE', 'BEL'],
    ['Belize', 'America', '501', 'BZ', 'BLZ'],
    ['Benin', 'Africa', '229', 'BJ', 'BEN'],
    ['Bermuda', 'America', '1-441', 'BM', 'BMU'],
    ['Bhutan', 'Asia', '975', 'BT', 'BTN'],
    ['Bolivia', 'America', '591', 'BO', 'BOL'],
    ['Bosnia and Herzegovina', 'Europe', '387', 'BA', 'BIH'],
    ['Botswana', 'Africa', '267', 'BW', 'BWA'],
    ['Brazil', 'America', '55', 'BR', 'BRA'],
    ['British Indian Ocean Territory', '', '246', 'IO', 'IOT'],
    ['British Virgin Islands', 'America', '1-284', 'VG', 'VGB'],
    ['Brunei', 'Asia', '673', 'BN', 'BRN'],
    ['Bulgaria', 'Europe', '359', 'BG', 'BGR'],
    ['Burkina Faso', 'Africa', '226', 'BF', 'BFA'],
    ['Burundi', 'Africa', '257', 'BI', 'BDI'],
    ['Cambodia', 'Asia', '855', 'KH', 'KHM'],
    ['Cameroon', 'Africa', '237', 'CM', 'CMR'],
    ['Canada', 'America', '1', 'CA', 'CAN'],
    ['Cape Verde', 'Africa', '238', 'CV', 'CPV'],
    ['Cayman Islands', 'America', '1-345', 'KY', 'CYM'],
    ['Central African Republic', 'Africa', '236', 'CF', 'CAF'],
    ['Chad', 'Africa', '235', 'TD', 'TCD'],
    ['Chile', 'America', '56', 'CL', 'CHL'],
    ['China', 'Asia', '86', 'CN', 'CHN'],
    ['Christmas Island', '', '61', 'CX', 'CXR'],
    ['Cocos Islands', '', '61', 'CC', 'CCK'],
    ['Colombia', 'America', '57', 'CO', 'COL'],
    ['Comoros', 'Africa', '269', 'KM', 'COM'],
    ['Cook Islands', 'Australia', '682', 'CK', 'COK'],
    ['Costa Rica', 'America', '506', 'CR', 'CRI'],
    ['Croatia', 'Europe', '385', 'HR', 'HRV'],
    ['Cuba', 'America', '53', 'CU', 'CUB'],
    ['Curacao', '', '599', 'CW', 'CUW'],
    ['Cyprus', 'Asia', '357', 'CY', 'CYP'],
    ['Czech Republic', 'Europe', '420', 'CZ', 'CZE'],
    ['Democratic Republic of the Congo', 'Africa', '243', 'CD', 'COD'],
    ['Denmark', 'Europe', '45', 'DK', 'DNK'],
    ['Djibouti', 'Africa', '253', 'DJ', 'DJI'],
    ['Dominica', 'America', '1-767', 'DM', 'DMA'],
    ['Dominican Republic', 'America', '1-809, 1-829, 1-849', 'DO', 'DOM'],
    ['East Timor', 'Asia', '670', 'TL', 'TLS'],
    ['Ecuador', 'America', '593', 'EC', 'ECU'],
    ['Egypt', 'Africa', '20', 'EG', 'EGY'],
    ['El Salvador', 'America', '503', 'SV', 'SLV'],
    ['Equatorial Guinea', 'Africa', '240', 'GQ', 'GNQ'],
    ['Eritrea', 'Africa', '291', 'ER', 'ERI'],
    ['Estonia', 'Europe', '372', 'EE', 'EST'],
    ['Ethiopia', 'Africa', '251', 'ET', 'ETH'],
    ['Falkland Islands', '', '500', 'FK', 'FLK'],
    ['Faroe Islands', 'Europe', '298', 'FO', 'FRO'],
    ['Fiji', 'Australia', '679', 'FJ', 'FJI'],
    ['Finland', 'Europe', '358', 'FI', 'FIN'],
    ['France', 'Europe', '33', 'FR', 'FRA'],
    ['French Polynesia', 'Australia', '689', 'PF', 'PYF'],
    ['Gabon', 'Africa', '241', 'GA', 'GAB'],
    ['Gambia', 'Africa', '220', 'GM', 'GMB'],
    ['Georgia', 'Asia', '995', 'GE', 'GEO'],
    ['Germany', 'Europe', '49', 'DE', 'DEU'],
    ['Ghana', 'Africa', '233', 'GH', 'GHA'],
    ['Gibraltar', 'Europe', '350', 'GI', 'GIB'],
    ['Greece', 'Europe', '30', 'GR', 'GRC'],
    ['Greenland', 'Europe', '299', 'GL', 'GRL'],
    ['Grenada', 'America', '1-473', 'GD', 'GRD'],
    ['Guam', 'Australia', '1-671', 'GU', 'GUM'],
    ['Guatemala', 'America', '502', 'GT', 'GTM'],
    ['Guernsey', '', '44-1481', 'GG', 'GGY'],
    ['Guinea', 'Africa', '224', 'GN', 'GIN'],
    ['Guinea-Bissau', 'Africa', '245', 'GW', 'GNB'],
    ['Guyana', 'America', '592', 'GY', 'GUY'],
    ['Haiti', 'America', '509', 'HT', 'HTI'],
    ['Honduras', 'America', '504', 'HN', 'HND'],
    ['Hong Kong', 'Asia', '852', 'HK', 'HKG'],
    ['Hungary', 'Europe', '36', 'HU', 'HUN'],
    ['Iceland', 'Europe', '354', 'IS', 'ISL'],
    ['India', 'Asia', '91', 'IN', 'IND'],
    ['Indonesia', 'Asia', '62', 'ID', 'IDN'],
    ['Iran', 'Asia', '98', 'IR', 'IRN'],
    ['Iraq', 'Asia', '964', 'IQ', 'IRQ'],
    ['Ireland', 'Europe', '353', 'IE', 'IRL'],
    ['Isle of Man', '', '44-1624', 'IM', 'IMN'],
    ['Israel', 'Asia', '972', 'IL', 'ISR'],
    ['Italy', 'Europe', '39', 'IT', 'ITA'],
    ['Ivory Coast', 'Africa', '225', 'CI', 'CIV'],
    ['Jamaica', 'America', '1-876', 'JM', 'JAM'],
    ['Japan', 'Asia', '81', 'JP', 'JPN'],
    ['Jersey', '', '44-1534', 'JE', 'JEY'],
    ['Jordan', 'Asia', '962', 'JO', 'JOR'],
    ['Kazakhstan', 'Asia', '7', 'KZ', 'KAZ'],
    ['Kenya', 'Africa', '254', 'KE', 'KEN'],
    ['Kiribati', 'Australia', '686', 'KI', 'KIR'],
    ['Kosovo', '', '383', 'XK', 'XKX'],
    ['Kuwait', 'Asia', '965', 'KW', 'KWT'],
    ['Kyrgyzstan', 'Asia', '996', 'KG', 'KGZ'],
    ['Laos', 'Asia', '856', 'LA', 'LAO'],
    ['Latvia', 'Europe', '371', 'LV', 'LVA'],
    ['Lebanon', 'Asia', '961', 'LB', 'LBN'],
    ['Lesotho', 'Africa', '266', 'LS', 'LSO'],
    ['Liberia', 'Africa', '231', 'LR', 'LBR'],
    ['Libya', 'Africa', '218', 'LY', 'LBY'],
    ['Liechtenstein', 'Europe', '423', 'LI', 'LIE'],
    ['Lithuania', 'Europe', '370', 'LT', 'LTU'],
    ['Luxembourg', 'Europe', '352', 'LU', 'LUX'],
    ['Macao', 'Asia', '853', 'MO', 'MAC'],
    ['Macedonia', 'Europe', '389', 'MK', 'MKD'],
    ['Madagascar', 'Africa', '261', 'MG', 'MDG'],
    ['Malawi', 'Africa', '265', 'MW', 'MWI'],
    ['Malaysia', 'Asia', '60', 'MY', 'MYS'],
    ['Maldives', 'Asia', '960', 'MV', 'MDV'],
    ['Mali', 'Africa', '223', 'ML', 'MLI'],
    ['Malta', 'Europe', '356', 'MT', 'MLT'],
    ['Marshall Islands', 'Australia', '692', 'MH', 'MHL'],
    ['Mauritania', 'Africa', '222', 'MR', 'MRT'],
    ['Mauritius', 'Africa', '230', 'MU', 'MUS'],
    ['Mayotte', '', '262', 'YT', 'MYT'],
    ['Mexico', 'America', '52', 'MX', 'MEX'],
    ['Micronesia', 'Australia', '691', 'FM', 'FSM'],
    ['Moldova', 'Europe', '373', 'MD', 'MDA'],
    ['Monaco', 'Europe', '377', 'MC', 'MCO'],
    ['Mongolia', 'Asia', '976', 'MN', 'MNG'],
    ['Montenegro', 'Europe', '382', 'ME', 'MNE'],
    ['Montserrat', 'America', '1-664', 'MS', 'MSR'],
    ['Morocco', 'Africa', '212', 'MA', 'MAR'],
    ['Mozambique', 'Africa', '258', 'MZ', 'MOZ'],
    ['Myanmar', 'Asia', '95', 'MM', 'MMR'],
    ['Namibia', 'Africa', '264', 'NA', 'NAM'],
    ['Nauru', 'Australia', '674', 'NR', 'NRU'],
    ['Nepal', 'Asia', '977', 'NP', 'NPL'],
    ['Netherlands', 'Europe', '31', 'NL', 'NLD'],
    ['Netherlands Antilles', 'America', '599', 'AN', 'ANT'],
    ['New Caledonia', 'Australia', '687', 'NC', 'NCL'],
    ['New Zealand', 'Australia', '64', 'NZ', 'NZL'],
    ['Nicaragua', 'America', '505', 'NI', 'NIC'],
    ['Niger', 'Africa', '227', 'NE', 'NER'],
    ['Nigeria', 'Africa', '234', 'NG', 'NGA'],
    ['Niue', 'Australia', '683', 'NU', 'NIU'],
    ['North Korea', 'Asia', '850', 'KP', 'PRK'],
    ['Northern Mariana Islands', 'Australia', '1-670', 'MP', 'MNP'],
    ['Norway', 'Europe', '47', 'NO', 'NOR'],
    ['Oman', 'Asia', '968', 'OM', 'OMN'],
    ['Pakistan', 'Asia', '92', 'PK', 'PAK'],
    ['Palau', 'Australia', '680', 'PW', 'PLW'],
    ['Palestine', 'Asia', '970', 'PS', 'PSE'],
    ['Panama', 'America', '507', 'PA', 'PAN'],
    ['Papua New Guinea', 'Australia', '675', 'PG', 'PNG'],
    ['Paraguay', 'America', '595', 'PY', 'PRY'],
    ['Peru', 'America', '51', 'PE', 'PER'],
    ['Philippines', 'Asia', '63', 'PH', 'PHL'],
    ['Pitcairn', 'Australia', '64', 'PN', 'PCN'],
    ['Poland', 'Europe', '48', 'PL', 'POL'],
    ['Portugal', 'Europe', '351', 'PT', 'PRT'],
    ['Puerto Rico', 'America', '1-787, 1-939', 'PR', 'PRI'],
    ['Qatar', 'Asia', '974', 'QA', 'QAT'],
    ['Republic of the Congo', 'Africa', '242', 'CG', 'COG'],
    ['Reunion', 'Africa', '262', 'RE', 'REU'],
    ['Romania', 'Europe', '40', 'RO', 'ROU'],
    ['Russia', 'Asia', '7', 'RU', 'RUS'],
    ['Rwanda', 'Africa', '250', 'RW', 'RWA'],
    ['Saint Barthelemy', '', '590', 'BL', 'BLM'],
    ['Saint Helena', 'Africa', '290', 'SH', 'SHN'],
    ['Saint Kitts and Nevis', 'America', '1-869', 'KN', 'KNA'],
    ['Saint Lucia', '', '1-758', 'LC', 'LCA'],
    ['Saint Martin', '', '590', 'MF', 'MAF'],
    ['Saint Pierre and Miquelon', '', '508', 'PM', 'SPM'],
    ['Saint Vincent and the Grenadines', 'America', '1-784', 'VC', 'VCT'],
    ['Samoa', 'Australia', '685', 'WS', 'WSM'],
    ['San Marino', 'Europe', '378', 'SM', 'SMR'],
    ['Sao Tome and Principe', 'Africa', '239', 'ST', 'STP'],
    ['Saudi Arabia', 'Asia', '966', 'SA', 'SAU'],
    ['Senegal', 'Africa', '221', 'SN', 'SEN'],
    ['Serbia', 'Europe', '381', 'RS', 'SRB'],
    ['Seychelles', 'Africa', '248', 'SC', 'SYC'],
    ['Sierra Leone', 'Africa', '232', 'SL', 'SLE'],
    ['Singapore', 'Asia', '65', 'SG', 'SGP'],
    ['Sint Maarten', '', '1-721', 'SX', 'SXM'],
    ['Slovakia', 'Europe', '421', 'SK', 'SVK'],
    ['Slovenia', 'Europe', '386', 'SI', 'SVN'],
    ['Solomon Islands', 'Australia', '677', 'SB', 'SLB'],
    ['Somalia', 'Africa', '252', 'SO', 'SOM'],
    ['South Africa', 'Africa', '27', 'ZA', 'ZAF'],
    ['South Korea', 'Asia', '82', 'KR', 'KOR'],
    ['South Sudan', 'Africa', '211', 'SS', 'SSD'],
    ['Spain', 'Europe', '34', 'ES', 'ESP'],
    ['Sri Lanka', 'Asia', '94', 'LK', 'LKA'],
    ['Sudan', 'Africa', '249', 'SD', 'SDN'],
    ['Suriname', 'America', '597', 'SR', 'SUR'],
    ['Svalbard and Jan Mayen', '', '47', 'SJ', 'SJM'],
    ['Swaziland', 'Africa', '268', 'SZ', 'SWZ'],
    ['Sweden', 'Europe', '46', 'SE', 'SWE'],
    ['Switzerland', 'Europe', '41', 'CH', 'CHE'],
    ['Syria', 'Asia', '963', 'SY', 'SYR'],
    ['Taiwan', 'Asia', '886', 'TW', 'TWN'],
    ['Tajikistan', 'Asia', '992', 'TJ', 'TJK'],
    ['Tanzania', 'Africa', '255', 'TZ', 'TZA'],
    ['Thailand', 'Asia', '66', 'TH', 'THA'],
    ['Togo', 'Africa', '228', 'TG', 'TGO'],
    ['Tokelau', '', '690', 'TK', 'TKL'],
    ['Tonga', 'Australia', '676', 'TO', 'TON'],
    ['Trinidad and Tobago', 'America', '1-868', 'TT', 'TTO'],
    ['Tunisia', 'Africa', '216', 'TN', 'TUN'],
    ['Turkey', 'Asia', '90', 'TR', 'TUR'],
    ['Turkmenistan', 'Asia', '993', 'TM', 'TKM'],
    ['Turks and Caicos Islands', '', '1-649', 'TC', 'TCA'],
    ['Tuvalu', 'Australia', '688', 'TV', 'TUV'],
    ['US Virgin Islands', 'America', '1-340', 'VI', 'VIR'],
    ['Uganda', 'Africa', '256', 'UG', 'UGA'],
    ['Ukraine', 'Europe', '380', 'UA', 'UKR'],
    ['United Arab Emirates', 'Asia', '971', 'AE', 'ARE'],
    ['United Kingdom', 'Europe', '44', 'GB', 'GBR'],
    ['United States', 'America', '1', 'US', 'USA'],
    ['Uruguay', 'America', '598', 'UY', 'URY'],
    ['Uzbekistan', 'Asia', '998', 'UZ', 'UZB'],
    ['Vanuatu', 'Australia', '678', 'VU', 'VUT'],
    ['Vatican', 'Europe', '379', 'VA', 'VAT'],
    ['Venezuela', 'America', '58', 'VE', 'VEN'],
    ['Vietnam', 'Asia', '84', 'VN', 'VNM'],
    ['Wallis and Futuna', '', '681', 'WF', 'WLF'],
    ['Western Sahara', 'Africa', '212', 'EH', 'ESH'],
    ['Yemen', 'Asia', '967', 'YE', 'YEM'],
    ['Zambia', 'Africa', '260', 'ZM', 'ZMB'],
    ['Zimbabwe', 'Africa', '263', 'ZW', 'ZWE']
];

const regexes = countries.map(item => {
	const [ country ] = item;
	const words = country.split(' ').map(item => item.trim().toLowerCase()).filter(item => item.length > 0);

	return `(?:\\b${words.join(`\\s*`)}\\b)`;
});

const regex = new RegExp(`(${regexes.join("|")})`, 'ig');

app.get('/country/match', (req, res, next) => {

	const { q = null } = req.query;

	if (!_.isString(q)) {
		return res.status(400).json({
			status: 'failed',
			error: 'Missing search query parameter.'
		});
	}

	const matches = q.match(regex);

	return res.status(200).json({
		status: 'success',
		countries: matches
			? matches.map(match => {

				const clean = val => val.toLowerCase().trim().replace(/\s+/g, '');

				const [
					country, continent, dialcode, iso2, iso3
				] = countries.find(([country]) => clean(match) === clean(country));

				return {
					country: country.toUpperCase(),
					continent: continent.toUpperCase(),
					dialcode: `+${dialcode}`,
					iso2: iso2.toUpperCase(),
					iso3: iso3.toUpperCase()
				}

			})
			: []
	});

});

app.listen(port, () => console.log(`App running on port ${port}.`));
